name: 'Get Time Action'
description: 'Get the time in the specified time zone'
author: 'JantHsueh'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  timeZone:
    description: 'time zone'
    required: true
    default: 8
outputs:
  log:
    description: 'current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
